# GLOBAL application
version: "3.9"


services:

  app:
    image: ${APP_GROUP}/${APP_NAME}:${APP_VERSION}
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
      args:
        - NETRC_PATH=${NETRC_PATH}
        - PIP_CONF_PATH=${PIP_CONF_PATH}
    container_name: ${APP_ID}
    env_file:
      - .env
    restart: on-failure

